### ISSUE TITLE
Sparse data

### ISSUE THREAD

**Issue by ISipi** [eribean/girth#110]
Hi,

Do you happen to know if using sparse data would work for IRT? In my case I have x subjects, n items, but each subject is shown only a random subset of the items, which means that most items won't be answered by more than 4-6 subjects (although this ranges from 0-17 for all items). Would using the missing data method solve this?

**Comment by eribean** [comment]
Using the ```tag_missing_data``` function would be able to handle this type of data. The scenario you described is going to produce estimates with large uncertainties. A test length of roughly 5 and a small sample size, there isn't a lot of information available. I would recommend using ```twopl_mml_eap``` or ``'grm_mml_eap``` for estimation. Alternatively, look at [girth_mcmc](https://github.com/eribean/girth_mcmc) for bayesian methods.

**Comment by ISipi** [comment]
Thanks, I figured that IRT might be out of the question for my data. Fortunately this isn't related to my primary research question. Thanks again.
