### ISSUE TITLE
Girth Rebrand

### ISSUE THREAD

**Issue by eribean** [eribean/girth#119]
I'm leaving Georgia Tech and need to Rebrand Girth. I need to replace the G with something:

Current thoughts are
* General
* Generalized
* Great

Anyone have any thoughts?

**Comment by eribean** [comment]
@tzellman, do you have any thoughts?

**Comment by tzellman** [comment]
golden baby

**Comment by eribean** [comment]
@tzellman I like it:

GIRTH: Golden Item Response Theory

**Comment by tzellman** [comment]
I also like the recursive idea though.. so meta.

**Comment by eribean** [comment]
@tzellman Why u no star yet?
