### ISSUE TITLE
How to estimate theta?

### ISSUE THREAD

**Issue by Goodelang** [eribean/girth#32]
The value of a and b can be estimated through MML. This software package does not seem to have the function of estimating the theta value of the subject. Whether to add the MAP method to estimate.
Thank you

**Comment by eribean** [comment]
Ability estimates are scheduled for the April release, I will try to hasten it if it's a pressing concern?

**Comment by eribean** [comment]
The branch "abilities_estimation" has included maximum a posteriori (MAP) and maximum likelihood (MLE).  Going to add Expected a posterior (EAP) and unittests next.

**Comment by eribean** [comment]
Added Expected a posteriori, need to write unittests before committing.

**Comment by eribean** [comment]
Committed this into master, add three ability estimation methods:
*  Maximum Likelihood
*  Maximum a Posteriori
*  Expected a Posteriori

```python
import numpy as np
from girth import twopl_separate
from girth import create_synthetic_irt_dichotomous
from girth import ability_eap

# Create Synthetic Data
difficulty = np.linspace(-2, 2, 10)
discrimination = 0.5 + np.random.rand(10) * 2
theta = np.random.randn(400)

syn_data = create_synthetic_irt_dichotomous(difficulty, discrimination, theta)

alpha, beta = twopl_separate(syn_data)
theta_star = ability_eap(syn_data, beta, alpha)

list(zip(theta.round(3), theta_star.round(3)))
```
