### ISSUE TITLE
Estimate ability with 3PL IRT

### ISSUE THREAD

**Issue by sitompul** [eribean/girth#69]
Hi is there a way to do theta estimation with guessing parameter?

I've seen ```guessing``` params been used in ```create_synthetic_irt_dichotomous()``` function but couldn't see any code that using it.

Is there a way to do  3PL IRT theta estimation using girth?

**Comment by eribean** [comment]
I’m not a big supporter of the 3PL model.  People don’t often randomly guess, their guessing pattern is correlated with their ability.  I have a bit of free time this weekend, I’ll see if I can add it in, but it would only be for the dichotomous case.  Is that sufficient?

**Comment by eribean** [comment]
I've added initial parameter estimates for the 3PL model. Working on adding ability estimates soon.

**Comment by eribean** [comment]
The ability estimates are added and support MLE, MAP, EAP estimations. I put it in its own directory. Going to write unit tests then will create a pull request that @sitompul can verify.

**Comment by eribean** [comment]
I added a unidimensional parameter and an ability estimator. The 3PL model doesn't behave as nicely as the other two unless you have lots of data, but it's there. 

Example Usage
```python
import numpy as np

from girth import create_synthetic_irt_dichotomous
from girth.three_pl import threepl_mml, ability_3pl_eap

# Create Synthetic Data
np.random.seed(42)
difficuly = np.linspace(-2.5, 2.5, 20)
discrimination = np.random.rand(20) + 0.5
guessing = np.random.rand(20) * 0.25
theta = np.random.randn(5000)

syn_data = create_synthetic_irt_dichotomous(difficuly, discrimination, theta, guessing)

# Parameter estimates
p_estimates = threepl_mml(syn_data)

# Ability Estimates
p_theta = ability_3pl_eap(syn_data, p_estimates[1], p_estimates[0], p_estimates[2])

```
