### ISSUE TITLE
Rasch np.unique and NaN values

### ISSUE THREAD

**Issue by Helma-T** [eribean/girth#91]
Hi,
First of all, thank you very much for the great library. 

Trying to use the Rasch model, it seems that the library does not accept any NaN or missing values. 
In particular, if the dataset of [item X Participant] with values of True and False contains NaN values, an exception rises for every Rasch-related model.
The exception is from unique_sets, counts = np.unique(dataset, axis=1, return_counts=True)
For example in line 14 of def _jml_abstract. 

Any suggestions on how to deal with missing NaN values?

Somehow in a time constraint for the academic project, that is why using a library instead of from-the-scratch implementation. So I highly appreciate any hint.

**Comment by eribean** [comment]
Hi,

It's my fault for not having better documentation, and I promise I'm working on it.  Missing data needs to be coded a certain way and there is a function for that:

```python
from girth import tag_missing_data
from girth import rasch_mml

# For dichotomous data (the second argument represents the valid data)
my_tagged_data = tag_missing_data(original_data, [0, 1])

# Run an estimation routine
results = rasch_mml(my_tagged_data)

```

Let me know if this helps!

**Comment by eribean** [comment]
Curious why you are using joint maximum likelihood?

**Comment by Helma-T** [comment]
Thank you for the quick response. I guessed this has not yet been updated in the release. So I installed it directly from the git repository and converted even missing values to -99999 in the dataset as well. But this unique numpy stills raises an exception for the "type error: The axis argument to unique is not supported for dtype object"
I think I will manually include the library and modify the use of unique and see if I can fix this. If I understood correctly, Unique is only used to drive count and build the signed matrix for the_sign, so perhaps I can replace it with values.

All Rasch implementation, jml, conditional, and mml behave similarly with the exception on np.unique. I  tried them all.

Join Maximum likelihood because of the high dimensionality of my data (450 item X 160 User) with high sparsity. I can compare and find the best approach for my problem statement according to the performance and results.

**Comment by eribean** [comment]
That error looks like you have an array of mixed types (strings and ints).  I expect an array of type int32.  Try converting any strings to ints “True” becomes 1 etc ...

**Comment by eribean** [comment]
If you can share your dataset or something in a similar format, I’ll take a look at it to see whats wrong.  I would appreciate it!

**Comment by Helma-T** [comment]
Thanks for the clarification.
Is True 1 and False 0, or as it stated in util, convert_response to kernel sign method, it is reversed, i.e., True/False is 0 /1? 
Because this function assumes a -1 for value 1.

**Comment by eribean** [comment]
True: 1 and False: 0

Thanks for helping me vet this, I’ll add updates to clarify this
